# Generated by Django 4.2 on 2023-04-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('-created',)},
        ),
    ]
